### ISSUE TITLE
Cannot recognize the ">>" symbol

### ISSUE THREAD

**Issue by huakucha** [tekartik/process_run.dart#10]
shell can save a new file wiht ">>"symbol,but process_run run 
"pod ipc spec "xx.podspec" >> "xxx.podspec.json"  note:
[!] Unknown command: `>>`

**Comment by YazeedAlKhalaf** [comment]
If you want, just put it in an .sh file an run t

**Comment by YazeedAlKhalaf** [comment]
Here is an example: https://gist.github.com/YazeedAlKhalaf/2e063e344b3f3f4bb99a79c601e17a13

**Comment by YazeedAlKhalaf** [comment]
I guess this issue is resolved @alextekartik

**Comment by alextekartik** [comment]
Thanks @YazeedAlKhalaf
