### ISSUE TITLE
strange backslash with quote when running with shell.runExecutableArguments

### ISSUE THREAD

**Issue by yunlianwangluo** [tekartik/process_run.dart#107]
we are try to run shell ffmpeg cmd on macos with parameters:
-i ./input.mp4 -filter_complex "scale='trunc((iw*1.2)/2)*2':'trunc((ih*1.2)/2)*2'" -shortest  -c:v libx264 -c:a aac ./scale.mp4 -y

parameters info after split by space:
[-i, ./input.mp4, -filter_complex, "scale='trunc((iw*1.2)/2)*2':'trunc((ih*1.2)/2)*2'", -shortest, -c:v, libx264, -c:a, aac, ./scale.mp4, -y]

but when pass it to runExecutableArguments, shell command becomes:
assets/ffmpeg/macos/ffmpeg -i ./input.mp4 -filter_complex "\\"scale='trunc((iw*1.2)/2)*2':'trunc((ih*1.2)/2)*2'\\"" -shortest -c:v libx264 -c:a aac ./scale.mp4 -y
command always running with extra \", how to fix it?

here is the function we wrote: 
Future<Map<String, dynamic>> executeCmd(String command, String cmdType) async {
    Map<String, dynamic> resultInfo = {};
    try{
        // Create output controller and filter out output lines
        var controller = ShellLinesController();
        String shellLog = '';
        controller.stream.listen((line) {
          //recording output lines
          line = line.trim().toLowerCase();
          shellLog = shellLog + line;
        });        
        // set controller on the stderr.
        var shell = Shell(stderr: controller.sink);
        // Run
        List<String> parameters = command.split(' ');
        print('running parameters:${parameters}');
        ProcessResult ret = await shell.runExecutableArguments("assets/ffmpeg/macos/${cmdType}", parameters);
        resultInfo['code'] = ret.exitCode;
        resultInfo['log'] = shellLog; 
        return resultInfo;          
    }catch(err){
        print('shell run err:${err}');
        resultInfo['code'] = -1;
        resultInfo['log'] = '$err';
        return resultInfo;
    }    
    resultInfo['code'] = -2;
    resultInfo['log'] = 'unknown err';
    return resultInfo;
  }
Any idea about this? Or we just use runExecutableArguments in a wrong way pls help to point it out...

**Comment by yunlianwangluo** [comment]
sorry, the wrong command handled by shell.runExecutableArguments should be(with extra backslash and quote): 
 assets/ffmpeg/macos/ffmpeg -i ./input.mp4 -filter_complex "\"scale='trunc((iw*1.2)/2)2':'trunc((ih1.2)/2)*2'"\" -shortest -c:v libx264 -c:a aac ./scale.mp4 -y

**Comment by yunlianwangluo** [comment]
well, we just check and erase the " in the parameter start and end, then it looks ok. though it is an ugly solution, ;=)

**Comment by alextekartik** [comment]
Yes should not add extra `"` when specifying the arguments explicitly (as it means that it is part of the string parameter which is not what ffmpg expect)
