### ISSUE TITLE
1.2.1 release not in git!

### ISSUE THREAD

**Issue by provokateurin** [tekartik/process_run.dart#110]
Hi, just saw there is the 1.2.1 update but it's neither tagged in the repo nor do the commits exists.
@alextekartik can you confirm this problem and that it is not due to someone malicious taking over the package?
I just want to make sure this is alright and gets noticed if it is a problem.
I downloaded the archives of 1.2.1 and 1.2.0+3 and the changes don't look suspicious to me, so it is probably fine after all.

**Comment by alextekartik** [comment]
Thanks for watching ! Sorry it was in a separate branch (just committed 5 minutes). The merge to main should be done now. indeed the merge happens after the publishing process (typically 1 minute later) so it might have a slight delay
