### ISSUE TITLE
[Feature Request] Showing the shell verbose in a Flutter Widget

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [tekartik/process_run.dart#12]
I would like to see a widget from your plugin that allows developers to show the verbose text from the shell in a Flutter Widget.

Just like android studio installation! I think it will be great!

For any future Googlers, the solution is by @alextekartik 

> As I said in #13 this is not a flutter package so there is no direct integration with any flutter widget. There is not much difference in how you would do with the system Process.start:
> 
> You should
> 
> * create a stream sink to capture command outputs
> * Stream the resulting content onto a widget.
> 
> I throw a quick example here:
> https://github.com/alextekartik/flutter_app_example/tree/master/process_run_example
> 
> On linux it should give you something like that (not tested on windows/mac yet, Mac would likely have a sandbox issue to fix in the xcode generated project)
> ![image](https://user-images.githubusercontent.com/1721046/87415222-1f297680-c5cd-11ea-9096-542bd7b6dca7.png)

**Comment by alextekartik** [comment]
As I said in #13 this is not a flutter package so there is no direct integration with any flutter widget. There is not much difference in how you would do with the system Process.start:

You should
- create a stream sink to capture command outputs
- Stream the resulting content onto a widget.

I throw a quick example here:
https://github.com/alextekartik/flutter_app_example/tree/master/process_run_example

On linux it should give you something like that (not tested on windows/mac yet, Mac would likely have a sandbox issue to fix in the xcode generated project)
![image](https://user-images.githubusercontent.com/1721046/87415222-1f297680-c5cd-11ea-9096-542bd7b6dca7.png)

**Comment by ReniDelonzek** [comment]
Is there any way to capture the logs printed by the executable in real time? I tested it by running a python script, but the result only returns every 5 min + -. It is a service that will be running endlessly, and I would like to be displaying his logs on Flutter

**Comment by YazeedAlKhalaf** [comment]
I will try it tomorrow (~9:00 GMT)
@alextekartik Thank you 🙏

**Comment by alextekartik** [comment]
@ReniDelonzek Yes if you look at the above example source code. Basically you can create stream controllers, that you use in the created shell

```dart
final _stdoutCtlr = StreamController<List<int>>();
final _stderrCtlr = StreamController<List<int>>();
shell = Shell(stdout: _stdoutCtlr.sink, stderr: _stderrCtlr.sink);
```

You can then listen to the controller stream to capture the logs in real-time.

**Comment by YazeedAlKhalaf** [comment]
@alextekartik Thank you so much!

It works like a charm. I believe it is better to add it to the docs, I could do a pull request 😎

I feel it is safe to close this issue now!

**Comment by ReniDelonzek** [comment]
@alextekartik 
I couldn't get it to work properly, I'm trying to track the output of a python script, however, it only captures when the script comes to an end, I used the example provided using the code below

`import time 

for i in range(0, 5):
    print('Teste: ' + str(i))
    time.sleep(1)`
