### ISSUE TITLE
[Question] Is there a way to run a command from assets?

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [tekartik/process_run.dart#13]

**Comment by alextekartik** [comment]
`process_run` is not a flutter package so has nothing specific for assets. You should be able to load a [string from assets](https://flutter.dev/docs/development/ui/assets-and-images#loading-text-assets) and [run](https://pub.dev/documentation/process_run/latest/shell_run/run.html) the loaded script. I have no example of this yet though...

**Comment by ductranit** [comment]
I'm having the same issue. My project is not only running the system command in platform os but also the embed custom command file in assets (for example, I want to run my own .exe file in project)
Atm I think there are 2 ways for this problem:
- Copy the command file from assets into the hosted platform directory before running it. Then try to get the absolute file path in dart side by using `path_provider` or `path_provider_fde`
- Put the command file into platform project (mac, windows, linux) & write a custom platform channel to get its absolute path and then using process_run to run it with absolute path

**Comment by YazeedAlKhalaf** [comment]
I am not really interested anymore in the issue, so if any of you is interested the owner can reopen it

@alextekartik Thanks

**Comment by thegrxp** [comment]
@ductranit a bit late to the party but have you found a solution?

**Comment by ductranit** [comment]
@thegrxp I suggested 2 solutions above. I chose the first one. I copied executable file from assets into application support folder by [path_provider](https://pub.dev/packages/path_provider) then run on this path
```
final dir = await getApplicationDocumentsDirectory();
final exePath = '${dir.path}/command'; 
// copy file from asset into doc dir

// then run
await shell.run('''
$exePath "param"
''');
```

**Comment by thegrxp** [comment]
Thank you I'll do the same

**Comment by memotai-admin** [comment]
> @thegrxp I suggested 2 solutions above. I chose the first one. I copied executable file from assets into application support folder by [path_provider](https://pub.dev/packages/path_provider) then run on this path
> 
> ```
> final dir = await getApplicationDocumentsDirectory();
> final exePath = '${dir.path}/command'; 
> // copy file from asset into doc dir
> 
> // then run
> await shell.run('''
> $exePath "param"
> ''');
> ```

How do you copy file from asset into path?

**Comment by filipenanclarez** [comment]
> How do you copy file from asset into path?

How do you copy file from asset into path?

**Comment by filipenanclarez** [comment]
> @thegrxp I suggested 2 solutions above. I chose the first one. I copied executable file from assets into application support folder by [path_provider](https://pub.dev/packages/path_provider) then run on this path
> 
> ```
> final dir = await getApplicationDocumentsDirectory();
> final exePath = '${dir.path}/command'; 
> // copy file from asset into doc dir
> 
> // then run
> await shell.run('''
> $exePath "param"
> ''');
> ```

How do you copy file from asset into path?
