### ISSUE TITLE
[Bug] `await Shell().run(script)` adds double quotes around brackets

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [tekartik/process_run.dart#15]
I am trying to run a command that adds to the User's PATH in Windows. The problem is that when I input the command to the run method it just adds quotes around brackets.

Code:
```dart
String path= "${userChoice.installationPath}\\wow\\bin";
    String regQuery = r"reg query HKCU\Environment /v PATH";
    String command =
        'for /f \"skip=2 tokens=3*\" %a in \(\'$regQuery\'\) do @if [%b]==[] ( @setx PATH \"%~a;$path\" ) else ( @setx PATH \"%~a %~b;$path\" )';
    print(command);
    await _shell.run(command);
```

When printing before running this is the output:
```bash
flutter: for /f "skip=2 tokens=3*" %a in ('reg query HKCU\Environment /v PATH') do @if [%b]==[] ( @setx PATH "%~a;C:\Users\yazee\Documents\Killer" ) else ( @setx PATH "%~a %~b;C:\Users\yazee\Documents\Killer" )
```

The output of the Shell.run():
```bash
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: ShellException(for /f "skip=2 tokens=3*" %a in "(reg query HKCU\\Environment /v PATH)" do @if [%b]==[] ( @setx PATH %~a;C:\Users\yazee\Documents\Killer ) else ( @setx PATH "%~a %~b;C:\Users\yazee\Documents\Killer" ), exitCode 1, workingDirectory: MY_DIRECTORY_HIDDEN)
```

I tried in cmd with quotes and it gave the same error. so the problem is that `process_run` is adding quotes around brackets in commands.

I hope you have a solution

**Comment by alextekartik** [comment]
Maybe the Shell name is mis-leading since as noted [in the doc](https://github.com/tekartik/process_run.dart/blob/67538a573ea1182212b1ccac389f8c87ccebcfa4/doc/shell.md):

> Each command must evaluate to one executable (i.e. no loop, pipe, redirection, bash/powershell specific features).

One solution if want to run a powershell script is to create a script file and run it using process_run (`Shell()..run('PowerShell myfile.ps1');

**Comment by YazeedAlKhalaf** [comment]
My next question is how to run a `.ps1`? It will be custom so from my assets? or how?

**Comment by alextekartik** [comment]
I don't have a windows machine at this time to give you a tested answer but you should be able to:
* Put your script as an asset and read it as a string: https://flutter.dev/docs/development/ui/assets-and-images#loading-text-assets
* Create a fille in a temp folder or in the application document directory and create a file with the text read
* Run it using `Shell()..run('PowerShell $myShellScriptPath');`or something similar

And at the end I would be happy to know if it works ;)

**Comment by YazeedAlKhalaf** [comment]
I have solved it by putting it in a `.bat` file and then running it using `cmd <FILE PATH>`
