### ISSUE TITLE
[Bug] Command Prompt is launched when executing commands on Windows

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [tekartik/process_run.dart#18]
When I try to run a command, I get a command prompt launched!

and if I close the cmd windows the process stops which is not good. I am using your package in my [Flutter Installer](https://github.com/YazeedAlKhalaf/Flutter_Installer)

I hope you can help me in solving this problem. Making commands run in the background without launching a cmd window into the foreground

**Comment by YazeedAlKhalaf** [comment]
It happens only in release mode

**Comment by alextekartik** [comment]
Thanks for the report. Can you confirm that you don't get the invite when:
* running the same command in windows run window
* using dart https://api.dart.dev/stable/2.8.4/dart-io/Process/run.html

Also can you specify which process was called, the stdout and stderr could help too if you can turn on some verbose mode even in release mode so I that I can investigate if needed.

Thanks!

**Comment by YazeedAlKhalaf** [comment]
Any command that requires time to execute like downloading a File or extracting a zip file or running a program shows the window. It seems it is the one responsible for the currently running command since it has to be open for the command to run. I tried closing it during the process, process just stopped.

It happens when using the `Process.run()`


I hope you can help me.


You can find all examples here:
https://github.com/YazeedAlKhalaf/Flutter_Installer

**Comment by YazeedAlKhalaf** [comment]
Any updates?

**Comment by alextekartik** [comment]
It would help if you could have a simple example showing the issue rather than a whole app to run and debug. Also if you can add more information:
- what is the command line causing the issue
- what are the logs if you turn verbose one

If it happen when using Process.run(), there is no much we can do. I was able to run in release mode the simple example https://github.com/alextekartik/flutter_app_example/tree/master/process_run_example, mabye you could try it with some of your commands.

**Comment by YazeedAlKhalaf** [comment]
Ah okay, btw the app runs with no extra config. Just run `flutter pub get`.

The part of the code you need is the scripts folder.
Link to it: https://github.com/YazeedAlKhalaf/Flutter_Installer/tree/master/lib/src/ui/views/steps/installing/scripts

Each file inside it is a file with a platform name for downloading on that specific platform. The one we are interested in is Windows.

**Comment by LeXuanKhanh** [comment]
@YazeedAlKhalaf have your problem resoved yet ? 
I have looked at #16 but still no answer
The workaround I'm using is to add "start /B", it still flash a Command Prompt windows a little bit

**Comment by YazeedAlKhalaf** [comment]
I have used a workaround in my Flutter Installer and it worked really good: https://github.com/flutter/flutter/issues/47891#issuecomment-708850435

I used it here https://github.com/YazeedAlKhalaf/Flutter_Installer/blob/master/windows/runner/main.cpp

**Comment by YazeedAlKhalaf** [comment]
I forgot to close the issue since it got sovled by a workaround.

**Comment by LeXuanKhanh** [comment]
thanks @YazeedAlKhalaf, it's work for my project too
