### ISSUE TITLE
ProcessException: Operation not permitted on macOS

### ISSUE THREAD

**Issue by putraxor** [tekartik/process_run.dart#3]
Trace logs
```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
$ dart --version
ProcessException: Operation not permitted                               
  Command: /usr/local/bin/dart --version                                
$ dart --version                                                        
workingDirectory: null                                                  
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ProcessException: Operation not permitted
  Command: /usr/local/bin/dart --version                                
#0      run (package:process_run/process_run.dart:166:15)               
<asynchronous suspension>                                               
#1      TrainBloc.startTraining (package:binomo_robot/ai/blocs/train_bloc.dart:27:5)
<asynchronous suspension>                                               
#2      new TrainBloc (package:binomo_robot/ai/blocs/train_bloc.dart:21:5)
#3      main (package:binomo_robot/main.dart:12:54)                     
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
#5      _rootRun (dart:async/zone.dart:1124:13)                         
#6      _CustomZone.run (dart:async/zone.dart:1021:19)                  
#7      _runZoned (dart:async/zone.dart:1516:10)                        
#8      runZoned (dart:async/zone.dart:1500:12)                         
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)    
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by alextekartik** [comment]
Weird indeed. I'm puzzled to see some flutter reference here (process_run is for the dart vm - not tested on flutter - and I'm not sure how Process behaves on Flutter (I guess desktop here)). Since process_run relied on https://api.dart.dev/stable/2.5.1/dart-io/Process/run.html can you try the raw implementation first?

**Comment by Danopie** [comment]
@putraxor Have you figured it out? The raw implementation yields the same result.

**Comment by putraxor** [comment]
@Danopie I use the default `Process.start` on Flutter Desktop (macOS) and disable sandbox mode on xcode

**Comment by Danopie** [comment]
Thank you @putraxor, in my case only turning off the sandbox mode does the trick

**Comment by Timmmm** [comment]
For future googlers, to disable sandbox mode comment this out in `macos/Runner/*.entitlements`:

```
<key>com.apple.security.app-sandbox</key>
<true/>
```

**Comment by janoschpelzer** [comment]
Well this is not a solution because I don't want to disable sandbox mode. How can I run a process without disabling sandbox mode?

**Comment by hongfeiyang** [comment]
I don't want to disable the sandbox mode either. It messes up with user's documents folder.

**Comment by LittleHans8** [comment]
> Well this is not a solution because I don't want to disable sandbox mode. How can I run a process without disabling sandbox mode?

It’s been three years, brother. Have you found a solution yet?​⬤

**Comment by janoschp** [comment]
@LittleHans8 bruh, what do you think? I don't even work with Flutter anymore, I don't even remember why I asked this question.
