### ISSUE TITLE
Can't change directory

### ISSUE THREAD

**Issue by LeXuanKhanh** [tekartik/process_run.dart#34]
Hello, I try some simple commands  with "cd" but seem like its doesn't do anything
Thing I try:
Use ` cd ..`
Use `cd <some children directory> ( ex: cd video )`
Use `cd /d <directory from anywhere on my pc>`

I checked by using cd to print out the current directory path but it's doesn't change, am I do anything wrong ?

My example code below ( with `cd ..` ), almost like the Shell example, just add some new command to run 

```
  void test() async {
    controller.stream.listen((event) {
      print(event);
    });

    try {
      await shell.run('cd ..');
      await shell.run('cd');
    } on ShellException catch (e) {
      // We might get a shell exception
      log('error');
      log(e.result.stderr);
    }
  }
```

**Comment by alextekartik** [comment]
Indeed Shell have a final working directory. The solution is to use `Shell.cd`:

```dart
var shell = Shell();
await shell.run('ls');
// Go into test
shell = shell.cd('test');
await shell.run('ls');
// Go up
shell = shell.cd('..');
await shell.run('ls');
```

You can also use `pushd/popd`.
```dart
shell = Shell();
await shell.run('ls');
// Go into test
shell = shell.pushd('test');
await shell.run('ls');
// Go back
shell = shell.popd();
await shell.run('ls');
```

**Comment by LeXuanKhanh** [comment]
thank you, both ways all work for me
