### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by HennieReyneke** [tekartik/process_run.dart#4]
Hi. When I create a new Flutter project in Android Studio and copy paste the the example code over main.dart , I get the following when running main.dart:

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): join(null, ".config"): part 0 was null, but part 1 was not.

E/flutter (24581): #0      _validateArgList (package:path/src/context.dart:1088:5)
E/flutter (24581): #1      Context.join (package:path/src/context.dart:231:5)
E/flutter (24581): #2      join (package:path/path.dart:259:13)
E/flutter (24581): #3      userAppDataPath (package:process_run/src/shell_utils.dart:76:5)
E/flutter (24581): #4      getUserEnvFilePath (package:process_run/src/user_config.dart:272:12)
E/flutter (24581): #5      getUserConfig (package:process_run/src/user_config.dart:249:13)
E/flutter (24581): #6      userConfig.<anonymous closure> (package:process_run/src/user_config.dart:36:14)
E/flutter (24581): #7      userConfig (package:process_run/src/user_config.dart:37:6)
E/flutter (24581): #8      userEnvironment (package:process_run/src/user_config.dart:66:44)
E/flutter (24581): #9      run (package:process_run/process_run.dart:147:21)
E/flutter (24581): <asynchronous suspension>
E/flutter (24581): #10     runCmd (package:process_run/cmd_run.dart:50:18)
E/flutter (24581): <asynchronous suspension>
E/flutter (24581): #11     Shell.run (package:process_run/shell.dart:222:35)
E/flutter (24581): <asynchronous suspension>
E/flutter (24581): #12     main (package:network_tools/main.dart:10:15)
E/flutter (24581): <asynchronous suspension>
E/flutter (24581): #13     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
E/flutter (24581): #14     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (24581): #15     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24581): #16     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (24581): #17     runZoned (dart:async/zone.dart:1500:12)
E/flutter (24581): #18     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
E/flutter (24581): #19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (24581): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by misaelmt** [comment]
How you are running it?
This project is for Linux/Win/Mac only.

**Comment by HennieReyneke** [comment]
I ran it on Android, sorry.

**Comment by alextekartik** [comment]
Actually it should work on Android (never tested but I know some people use it with ffmpeg with some workaround). Version 0.10.4 should fix the issue. I personnally have just tested `run('echo Hello')`.
