### ISSUE TITLE
process_run: ^0.12.1 upgrade causing an issue with pubnub: ^3.2.0

### ISSUE THREAD

**Issue by unoravi** [tekartik/process_run.dart#40]
Running dev_dependencies in pubspec.yaml :
process_run: ^0.11.2+1
pubnub: ^3.2.0

I found that there is an update for package process_run (process_run: ^0.12.1) but when I save and run "flutter pub get" it it is facing an incompatible issue with pubnub existing package.

flutter pub get incompatible error details
```
Running "flutter pub get" in unoplayer...                       
Because encrypt >=4.0.1 <5.0.0-beta.1 depends on args ^1.6.0 and encrypt >=3.2.0 <4.0.1 depends on args ^1.5.2, encrypt >=3.2.0 <5.0.0-beta.1 requires args ^1.5.2.
And because pubnub >=3.2.0 depends on encrypt ^4.0.0, pubnub >=3.2.0 requires args ^1.5.2.


And because process_run 0.12.1 depends on args >=2.0.0 <4.0.0 and no versions of process_run match >0.12.1 <0.13.0, pubnub >=3.2.0 is incompatible with process_run ^0.12.1.

So, because signageplayer depends on both process_run ^0.12.1 and pubnub ^3.2.0, version solving failed.
pub get failed (1; So, because signageplayer depends on both process_run ^0.12.1 and pubnub ^3.2.0, version solving failed.)
exit code 1
```

**Comment by alextekartik** [comment]
process_run >= 0.12.0 is the null safety version. While it could coexists in non null safety environment, if a non-null safety package (pubnub) is having conflicting dependency, there is not much we can do. You should stick with process_run 0.11.0.

**Comment by unoravi** [comment]
@alextekartik 
I came to know that this issue is because of another dependency.

Thanks
