### ISSUE TITLE
[Question] How to include my own ADB (or any other package) and use it in the shell?

### ISSUE THREAD

**Issue by petodavid** [tekartik/process_run.dart#44]
I want to develop an application where I use ADB commands, I would like to ship my flutter application with a built in ADB so the user should not install it, it this possible?

**Comment by Hu-Wentao** [comment]
Did you succeed？

**Comment by petodavid** [comment]
Hi, what OS do you use?

**Comment by petodavid** [comment]
How do you run commands on windows?

**Comment by Hu-Wentao** [comment]
> How do you run commands on windows?

just ues process_run package，as example

**Comment by petodavid** [comment]
Does it work only if you run the app using the IDE run? What if you start the standalone built .exe ?

**Comment by Hu-Wentao** [comment]
> Does it work only if you run the app using the IDE run? What if you start the standalone built .exe ?

yes，it work。
I did not learn how to package exe，just use msix package

**Comment by petodavid** [comment]
Could you please send an example, mine code works only when I run the code in the IDE or using flutter run command

**Comment by petodavid** [comment]
Did you find a solution for MSIX?

**Comment by Hu-Wentao** [comment]
> Did you find a solution for MSIX?

No, I'm busy with other work.
and it code
```dart
  //  `controller` and `errorCtrl` can listening exe out puts

final file = await executable; // copy asstes exe to temp path, and get file
var exePath = file.absolute.path; // get file absolute path
final cmd ='$exePath$arguments'; // just as input to cmd
await Shell( stdout: controller!.sink, stderr: errorCtrl!.sink, verbose: false).run(cmd); // call `run()` method 
```
