### ISSUE TITLE
Nothing happens...

### ISSUE THREAD

**Issue by EightRice** [tekartik/process_run.dart#52]
Following the example code, nothing happens. No cmd window , no error in the console (or printing) .

I'm also not able to run anything with the dart:io package using Process.run, cause I'm getting `[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ProcessException: The system cannot find the file specified.`

Any help would be valued

**Comment by alextekartik** [comment]
Hi can you elaborate or share some code, logs on what you have tried.. Are you running on Windows, Linux or Mac? Have your tried to run the example: https://github.com/tekartik/process_run.dart/blob/master/example/example.dart ?
