### ISSUE TITLE
shell.run() removes trailing space from echo command.

### ISSUE THREAD

**Issue by SahajRana** [tekartik/process_run.dart#6]
Hi @alextekartik, It's really a great library & had saved me from lots of complications. I had an issue lately that in the following code I want to save file with echo & has some spaces in starting which are trimmed by shell command. How can we exclude from that happening.

```
await shell.run('''
          echo [__]-assests sas.png >>as.txt   
        ''');
```
[__]: > it's to show spaces in start after `echo` command.
Thanks!

**Comment by alextekartik** [comment]
I see 2 issues here. 

First piping (`>> as.txt`) is not supported (and I don't tihnk there is a way to support that). So you'd better write the file using `dart:io` (If need to write the file from the output of a command you can get the stdout of each command).

Secondly, spaces must be escaped for the parser to work. You can use double quotes or the `shellArgument` method:
```dart
await run('echo "Hello world"');
await run('echo ${shellArgument('Hello world')}');
```

I have updated the documentation here: https://github.com/tekartik/process_run.dart/blob/master/doc/shell.md#running-the-script

**Comment by SahajRana** [comment]
Thanks a lot, man!
