### ISSUE TITLE
which

### ISSUE THREAD

**Issue by 229106948** [tekartik/process_run.dart#60]
whichSync return null ,But I installed

**Comment by alextekartik** [comment]
`which` looks for executables in `PATH`, so you might have to tweak your env variables first. More information would help (which executable, platform...)

**Comment by goldcoders** [comment]
@alextekartik  isnt passing the PATH in process not enough? 
or do we still need to update .profile , .bashrc, .zshrc , .zprofile?
in linux and mac?

in windows its a different thing. it still return null if you just recently modify the environmental variable
the app need to be close to have it reflect changes.

**Comment by alextekartik** [comment]
Yes it looks in PATH.

>  it still return null 

I still don't know which executable your are looking for....

Example on linux:
```dart
import 'package:process_run/shell.dart';

void main(List<String> arguments) async {
  print(await which('ls'));
}
```

The command has to exists. On windows it also looks for `.bat`, `.exe`, '.cmd` extension
