### ISSUE TITLE
command and result printing problem

### ISSUE THREAD

**Issue by furkan1023** [tekartik/process_run.dart#61]
first of all thanks for this package its so useful for me. I am running shell commands in a timer which means it is writing too many print on console.I would delete these prints but  I couldn't find where are these prints. Could you tell me locations of prints.

For example when i try "wmic logicaldisk get volumename,name"

output is:
$ wmic logicaldisk get volumename,name
Name  VolumeName
C:    System
D:    ESD-USB
E:    TOSHIBA EXT

I dont want to see these outputs ^^

**Comment by alextekartik** [comment]
You can use `verbose: false` to hide the default stdout output:
```dart
import 'package:process_run/shell.dart';

Future<void> main(List<String> arguments) async {
  var shell = Shell();
  await shell.run('echo Visible');

  /// Hide output
  shell = Shell(verbose: false);
  await shell.run('echo "Not visible"');
}
```

**Comment by furkan1023** [comment]
> You can use `verbose: false` to hide the default stdout output:
> 
> ```dart
> import 'package:process_run/shell.dart';
> 
> Future<void> main(List<String> arguments) async {
>   var shell = Shell();
>   await shell.run('echo Visible');
> 
>   /// Hide output
>   shell = Shell(verbose: false);
>   await shell.run('echo "Not visible"');
> }
> ```

thank you so much 👍
