### ISSUE TITLE
Open the app on macOS, the program crashes

### ISSUE THREAD

**Issue by jsl328** [tekartik/process_run.dart#64]
Open the app on macOS, the program crashes

I use `which` command line to view the command line path, as `which $commandPath`, and then execute `shell.run($dart --version)` naming, the program exits, and there is no log. 

The preliminary conclusion is that the which command line returns **null**.

It is worth noting that I can use the executable file in the 
<img width="283" alt="截屏2021-12-22 上午11 53 14" src="https://user-images.githubusercontent.com/7724755/147032951-b941ae65-d125-442b-9b4a-10d44d27159b.png">
app normally

**Comment by alextekartik** [comment]
There is a note about MacOS flutter in the readme:

https://github.com/tekartik/process_run.dart#flutter-context

Does it fix your issue?

**Comment by jsl328** [comment]
No fix.
In my case, I modified the Flutter context, but the problem is not here. 
[](https://github.com/jsl328/pfGorgeousFlutterShell/edit/main/README.md)
I manually added `env.ymal`to the machine to fix the bug, thank you
