### ISSUE TITLE
[Question] Run process on mac while running integration test on Android emulator

### ISSUE THREAD

**Issue by mrhabibi** [tekartik/process_run.dart#69]
Hi, I need to run another bash script from my mac while running integration test on Android emulator, so the code will be invoked from the integration test code.

When I tried that out, It seems that `process_run` is running on the android environment, so I couldn't access any command from my mac such as `git`, `flutter`, `dart`, etc. But instead I can access my android command such as `input`, etc.

Can you help me solving my problem? Thank you.

**Comment by alextekartik** [comment]
You cannot spawn a mac executable while running tests on android. Typically you could create a dart script that will spawn  both integration test runner and a mac executable and have them communicate with websocket or http for example.

**Comment by mrhabibi** [comment]
I see, so it's not doable at least for now. Yeah, your suggestion may work for my case, thanks for your speedy response!
