### ISSUE TITLE
Enter argument in already running cmd process, waiting for input.

### ISSUE THREAD

**Issue by SahajRana** [tekartik/process_run.dart#7]
Hi @alextekartik, I just got stuck & was wondering if there is a way to input argument is already running cmd process, let's say `flutter run` then hot reload with input `R` later into it. 
Thanks & a happy new year!

**Comment by alextekartik** [comment]
Hi, dealing with stdin is always a pain. `R` for hot reload is not really an argument, it is something that you must send to the stdin of the spawned process. In theory, you should be able to add to stdin of the process you spawn by creating a custom stdin controller that you pass as an argument (its stream) of the run command.

I don't have a good example yet unfortunately. By default, the current stdin is used but I've seen some cases where it does not work. the io package as a concept of shared stdin that could be tried too.

**Comment by SahajRana** [comment]
@alextekartik thanks for the answer!, I have currently solved the problem by using `Process.start` directly, then listen to stdout & passing stdin.write for further command.
