### ISSUE TITLE
how to run top

### ISSUE THREAD

**Issue by chincccc** [tekartik/process_run.dart#75]
Like title

**Comment by chincccc** [comment]
`var shell = Shell(verbose: false);
var res =  await shell.run('top -n 1');`
ERROR: ShellException (ShellException(top -n 1, exitCode 1, workingDirectory: /home/user/Desktop/flutter/cinfo))

**Comment by alextekartik** [comment]
In verbose mode (that you explicitly set to false which does not help) it should report an error that could help such as: 

```
TERM environment variable not set.
```

or

```
top: failed tty get
```

I don't know this specific command enough but I think you should try to run in batch mode `-b`

```dart
import 'package:process_run/shell.dart';

void main(List<String> arguments) async {
  var shell = Shell();
  await shell.run('top -n 1 -b');
}
```

**Comment by chincccc** [comment]
Great！！
