### ISSUE TITLE
How to run shell in download directory.

### ISSUE THREAD

**Issue by DenisMrGnusa** [tekartik/process_run.dart#76]
how to run shell in my specific folder like downloads folder => _shell.cd('${downloadDir!.path}')_ ?

**Comment by alextekartik** [comment]
You can either specific the folder at creation time:
```dart
var shell = Shell(workingDirectory: myDir);
```

Or you could use `cd`. Note that it returns a new shell that you should use (i.e. you cannot use the existing one, the working directory is non-mutable property.

```dart
// Change directory
// Here we assign the new created shell to the existing variable
var shell = Shell();
shell = shell.cd(myDir);
```

**Comment by DenisMrGnusa** [comment]
yes that's it.
thank you, help me a lot.
