### ISSUE TITLE
[Windows] Unable to run executable with space in directory

### ISSUE THREAD

**Issue by javaherisaber** [tekartik/process_run.dart#81]
I want to run this command in a windows client:
```bat
reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | find /i "proxyserver"
```

I tried all possible ways to escape special chars

```dart
var exe1 = 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | find /i "proxyserver"';
var exe2 = 'reg query "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings" | find /i "proxyserver"';
var exe3 = 'reg query \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\" | find /i \"proxyserver\"';
var exe4 = 'reg query \"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\" | find /i \"proxyserver\"';
var exe5 = r'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | find /i proxyserver';
var exe5 = r'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | find /i "proxyserver"';

final result = await runExecutableArguments(exe1, [], verbose: true);
```

But I get this error message:
```bat
ERROR: Invalid syntax.
Type \"REG QUERY /?\" for usage.
```

**Comment by alextekartik** [comment]
Hi. As stated [here](https://github.com/tekartik/process_run.dart/blob/master/doc/shell.md#running-the-script):

> Each command must evaluate to one executable (i.e. no loop, pipe, redirection, bash/powershell specific features)

> If you have spaces in one argument, it must be escaped using double quotes or the shellArgument method:

So you cannot use `... | find...` or other platform specific pipe/redirection and best is to use `shellArgument` to wrap parameters with spaces in it.

I have a little helper below that I use in one project to read a registry string entry that might help you. It is not fully tested but it might help you finding a proper solution:

```dart
/// read registry key at give path.
///
/// Not fully safe (for example does not handle content starting with a space) but ok for many scenarios
Future<String?> readRegistryString(String path, String key) async {
  try {
    // We'll get lines like
    // HKEY_LOCAL_MACHINE\SOFTWARE\Android Studio
    //    Path    REG_SZ    C:\Program Files\Android\Android Studio New
    //
    var lines = (await run(
            'reg query ${shellArgument(path)} /v ${shellArgument(key)}',
            verbose: false))
        .outLines
        .map((e) => e.trimLeft())
        .where((element) => element.split(' ').first == key);
    if (lines.isNotEmpty) {
      // Ok skip the key and look for REG_SZ
      var regSz = 'REG_SZ';
      var line = lines.first.substring(key.length).trimLeft();
      if (line.startsWith(regSz)) {
        var content = line.substring(regSz.length).trimLeft();
        return content;
      }
    }
  } catch (_) {}
  return null;
}
```

For example the following should print the current windows version (`22H2` for me at this time, might be different for you):

```dart
Future<void> main() async {
  if (Platform.isWindows) {
    var displayVersion = await readRegistryString(
        'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion',
        'DisplayVersion');
    print(displayVersion);
  }
}
```

Let me know if that works for you!

**Comment by javaherisaber** [comment]
@alextekartik 
Seems like there is a bug in the `process_run` package
Running this code returns ```ERROR: Invalid syntax. Type \"REG QUERY /?\" for usage.```

```dart
final executable = 'reg query ${shellArgument('HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings')}';
final result = await runExecutableArguments(executable, []);
```

But running this code returns the result successfully
```dart
final executable = 'reg query ${shellArgument('HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings')}';
final result = await Process.run(executable, []);
```

**Comment by alextekartik** [comment]
`runExecutableArguments` runs a single instruction where you have to explicitly separate executable and arguments with something like this:
```dart
final result = await runExecutableArguments('reg', [
      'query',
      'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings'
    ]);
```

no need to escape the arguments here. Event `Process.run` from `dart:io` should be used this way as specified in its [documentation](https://api.dart.dev/stable/2.18.3/dart-io/Process/run.html). Maybe on windows it is accepted but that is not a correct usage.

**Comment by alextekartik** [comment]
I misread you original issue where I did not see that you used runExecutableArguments. When you want to write the whole command line in a single string, you should use `run` (from process_run.dart) not runExecutableArguments or more generally `Shell().run(xxx)`. from `process_run/shell.dart` that I recommend.
