### ISSUE TITLE
is it possible to use loops and variables in shell.run ?

### ISSUE THREAD

**Issue by bohdanrx** [tekartik/process_run.dart#87]
I tried run simple for loop 

for i in {1..10}
do
  echo "This is iteration \$i"
done

and i got this response  Unhandled Exception: ShellException(for i in {1..10}, error: ProcessException: No such file or directory
  Command: for i in {1..10},
  
  and with variables same situation occurred 

  VAR=\$(dart --version)

response:  Check that VAR=$(dart exists
    command: VAR=$(dart --version)

**Comment by alextekartik** [comment]
Indeed, as stated in https://github.com/tekartik/process_run.dart/blob/master/doc/shell.md#running-the-script
> Each command must evaluate to one executable (i.e. no loop, pipe, redirection, bash/powershell specific features).

The idea is to indeed put the logic on the dart side:
```dart
var shell = Shell();
for (var i = 1; i <= 10; i++) {
  await shell.run('echo "This is iteration $i"');
}
```
