### ISSUE TITLE
ProcessException : ps -ef|grep $name |grep -v grep|awk '{print $2}'  

### ISSUE THREAD

**Issue by blackbridcn** [tekartik/process_run.dart#88]
Linux ProcessException : ps -ef|grep $name |grep -v grep|awk '{print $2}'

**Comment by alextekartik** [comment]
As stated in the doc: https://github.com/tekartik/process_run.dart/blob/master/doc/shell.md#running-the-script
> Each command must evaluate to one executable (i.e. no loop, pipe, redirection, bash/powershell specific features).

The problem is similar in other languages and I cannot figure out a good api to support this commonly requested feature.

One ugly solution is to do something like that:

```dart
// Create the pipe
var controller = StreamController<List<int>>();
// Hide the output.
var shell1 = Shell(verbose: false, stdout: controller.sink);
// Hide the command, show the output.
var shell2 = Shell(commandVerbose: false, stdin: controller.stream);

// You must not wait for the first process to finish to start the second
// process and close the pipe when done.
unawaited(shell1.run('ls').then((_) {
  controller.close();
}));
await shell2.run('grep i');
```

**Comment by blackbridcn** [comment]
thank you @alextekartik ，The requirement has been implemented, and finally, additional shell scripts are used to implement this function，
`  try {
      String path="sudo /bin/bash ${path}/status.sh ${name}";
      List<ProcessResult> result = await shell.run(path);
      result.forEach((element) {
        //task...
      });
    } catch (e) {
    }`

and  status.sh ：
`#!/bin/bash
NAME=${1}
serverStateFun() {
  PID=`ps -ef|grep $NAME |grep -v grep|awk '{print $2}'`
  echo $PID;
}
RESULTS=$(serverStateFun)
echo $RESULTS`

However, when the service（${name}） is running, in addition to the corresponding pid of the service, two sets of four pids are added, and even after the service is killed, two sets of four pids are still returned。

what？

> Linux ProcessException : ps -ef|grep $name |grep -v grep|awk '{print $2}'



> As stated in the doc: https://github.com/tekartik/process_run.dart/blob/master/doc/shell.md#running-the-script
> 
> > Each command must evaluate to one executable (i.e. no loop, pipe, redirection, bash/powershell specific features).
> 
> The problem is similar in other languages and I cannot figure out a good api to support this commonly requested feature.
> 
> One ugly solution is to do something like that:
> 
> ```dart
> // Create the pipe
> var controller = StreamController<List<int>>();
> // Hide the output.
> var shell1 = Shell(verbose: false, stdout: controller.sink);
> // Hide the command, show the output.
> var shell2 = Shell(commandVerbose: false, stdin: controller.stream);
> 
> // You must not wait for the first process to finish to start the second
> // process and close the pipe when done.
> unawaited(shell1.run('ls').then((_) {
>   controller.close();
> }));
> await shell2.run('grep i');
> ```

**Comment by blackbridcn** [comment]
thank you @alextekartik ，The requirement has been implemented, and finally, additional shell scripts are used to implement this function，
`  try {
      String path="sudo /bin/bash ${path}/status.sh ${name}";
      List<ProcessResult> result = await shell.run(path);
      result.forEach((element) {
        //task...
      });
    } catch (e) {
    }`

and  status.sh ：
`#!/bin/bash
NAME=${1}
serverStateFun() {
  PID=`ps -ef|grep $NAME |grep -v grep|awk '{print $2}'`
  echo $PID;
}
RESULTS=$(serverStateFun)
echo $RESULTS`

However, when the service（${name}） is running, in addition to the corresponding pid of the service, two sets of four pids are added, and even after the service is killed, two sets of four pids are still returned。

what？
